language: node_js
node_js:
  - "9.9.0"

sudo: false

branches:
   only:
   - develop

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  
install:
  - yarn

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"

script:
  - yarn test
  - yarn e2e